name: Manual deploys (for any environment or product)

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag version to be deployed (1.0.0-dev.0, 2.1.1)'
        required: true
        default: '-'
      env:
        description: 'Environment to be deployed (dev, staging, prod)'
        required: true
        default: 'prod'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout specific package tag release
        run: git checkout -b deploy-${{ github.event.inputs.tag }} ${{ github.event.inputs.tag }}
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '14.7.0'
          registry-url: https://npm.pkg.github.com
          scope: '@davikawasaki'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      - run: npm run build
        env:
          CI: true
      - name: "cat package.json"
        run: cat ./package.json
      - run: echo "Deploying release ${{ github.event.inputs.tag }} on ${{ github.event.inputs.env }}"
